openapi: 3.0.3
info:
  title: Swagger Clothes POC - OpenAPI 3.0
  description: >-
    This is a sample Clothes POC API Server based on the OpenAPI 3.0
    specification.  
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://clothespoc.swagger.io/api/v1
tags:
  - name: clothes
    description: List of all the clothes
paths:
  /clothes:
    put:
      tags:
        - clothes
      summary: Update existing clothing
      description: Update existing clothing by Id
      operationId: updateClothing
      requestBody:
        description: Update existing clothing
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clothing'
          application/xml:
            schema:
              $ref: '#/components/schemas/Clothing'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Clothing'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clothing'
            application/xml:
              schema:
                $ref: '#/components/schemas/Clothing'
        '400':
          description: Invalid ID supplied
        '404':
          description: Request not found
        '405':
          description: Validation exception
    post:
      tags:
        - clothes
      summary: Add a new clothing
      description: Add a new clothing
      operationId: addClothing
      requestBody:
        description: Create a new clothing
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clothing'
          application/xml:
            schema:
              $ref: '#/components/schemas/Clothing'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Clothing'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clothing'
            application/xml:
              schema:
                $ref: '#/components/schemas/Clothing'
        '405':
          description: Invalid input
  /clothes/{id}:
    get:
      tags:
        - clothes
      summary: Find clothing by ID
      description: Returns a clothing
      operationId: getClothingById
      parameters:
        - name: id
          in: path
          description: ID of clothing
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clothing'
            application/xml:
              schema:
                $ref: '#/components/schemas/Clothing'
        '400':
          description: Invalid ID supplied
        '404':
          description: Request not found
    delete:
      tags:
        - clothes
      summary: Deletes a clothing
      description: delete a clothing
      operationId: deleteClothing
      parameters:
        - name: id
          in: path
          description: Clothing id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid value
  /outfits:
    put:
      tags:
        - outfits
      summary: Update existing outfit
      description: Update existing outfit by Id
      operationId: updateOutfit
      requestBody:
        description: Update existing outfit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outfit'
          application/xml:
            schema:
              $ref: '#/components/schemas/Outfit'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Outfit'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outfit'
            application/xml:
              schema:
                $ref: '#/components/schemas/Outfit'
        '400':
          description: Invalid ID supplied
        '404':
          description: Request not found
        '405':
          description: Validation exception
    post:
      tags:
        - outfits
      summary: Add a new outfit
      description: Add a new outfit
      operationId: addOutfit
      requestBody:
        description: Create a new outfit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outfit'
          application/xml:
            schema:
              $ref: '#/components/schemas/Outfit'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Outfit'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outfit'
            application/xml:
              schema:
                $ref: '#/components/schemas/Outfit'
        '405':
          description: Invalid input        
  /outfits/{id}:
    get:
      tags:
        - outfits
      summary: Find outfit by ID
      description: Returns a outfit
      operationId: getOutfitById
      parameters:
        - name: id
          in: path
          description: ID of outfit
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Outfit'
            application/xml:
              schema:
                $ref: '#/components/schemas/Outfit'
        '400':
          description: Invalid ID supplied
        '404':
          description: Request not found
    delete:
      tags:
        - outfits
      summary: Deletes a outfit
      description: delete a outfit
      operationId: deleteOutfit
      parameters:
        - name: id
          in: path
          description: Oufit id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid value
components:
  schemas:
    Clothing:
      required:
        - photoUrl
        - type
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        photoUrl:
          type: string
        type:
          type: string
          enum:
            - shirt
            - top
            - bottom
            - socks
      xml:
        name: clothing
        
    Outfit:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
       
        clothes:
          type: array
          xml:
            name: clothes
            wrapped: true
          items:
            $ref: '#/components/schemas/Clothing'
      xml:
        name: customer
        
  requestBodies:
    Clothing:
      description: Clothing that is to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Clothing'
        application/xml:
          schema:
            $ref: '#/components/schemas/Clothing'
